### ISSUE TITLE
Distribuição da tabela do combinados 

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#100]
Mesmo com tela aberta, grande tá associando no responsivo. Podemos rever o tamanho das colunas?
![screen shot 2018-01-19 at 09 03 02](https://user-images.githubusercontent.com/3904166/35148031-daf27da4-fcf7-11e7-891e-679472ab42be.png)

**Comment by greevin** [comment]
A tabela foi ajustada com o tamanho de 100%, tal como ocorre nas outras tabelas, e agora mostra a coluna que estava escondida.
