### ISSUE TITLE
Help tá só em PT

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#101]
Podemos traduzir? Se puderem dar um tapa inicial (http://tradukka.com/translate?hl=pt) e me passarem, eu arrumo.

**Comment by glaubersp** [comment]
Tel, segue o texto pra caso vc queira alterar. Aqui é o lugar mais fácil pra manter os dois iguais e depois copiar pra lá, neste momento.

#  pt-BR

## Planejamento
Na seção de Planejamento é possível:

- criar indicadores a serem acompanhados em uma série temporal;
- definir objetivos a serem atingidos pelas metas; e
- planejar ações da escola com o intuito de atingir os objetivos definidos;

## Acompanhamento
Na seção de Acompanhemento é possível:

- adicionar registros dos indicadores e acompar a evolução destes dados ao longo do tempo;
- visualizar os objetivos definidos pela escola; e
- visualizar as ações planejadas pela escola

## Combinados
Na seção de Combinados é possível:

- criar combinados definidos em reuniões escolares ou extraídos da rotina escolar;
- listar todos os combinados existentes

## Gerenciar
A seção Gerenciar permite à administração escolar:

- acessar o painel de Administração do sistema.

#  en

## Plan
The Plan section allow us:

- to create new indicator to be monitored using a temporal chart;
- to define objectives to be achieved by the previously created indicators; and
- to plan new actions whose objectives are to achieve the defined goals;

## Check
The Check section allow us:

- to monitor the measured indicators along the time;
- to check the goals that have been defined; and
- to track actions and collect evidences that they have been executed.

## Agreements
The Agreements section allow us:

- to write down new agreements that were achieved at school meetings or extracted from the daily routine;
- to list all the agreements that have been already defined.

## Manage
The Manage section allow school staff:

- to access the administration painel.

**Comment by tamielbr** [comment]
Mudei algumas coisas no PT também:

## Planejamento
Na seção de Planejamento é possível:

- criar indicadores que poderão ser acompanhados ao longo do tempo, incluindo gráficos;
- definir objetivos que estejam ligados e possam impactar esse indicadores; e
- planejar ações da escola com o intuito de atingir os objetivos definidos;

## Acompanhamento
Na seção de Acompanhemento é possível:

- adicionar registros dos indicadores e acompar a evolução destes dados ao longo do tempo;
- visualizar os objetivos definidos pela escola; e
- visualizar as ações planejadas pela escola e coletar evidências.

## Combinados
Na seção de Combinados é possível:

- criar combinados escolares oriundos de reuniões escolares ou extraídos da rotina escolar;
- definir combinados com base em ações de sucesso;
- listar todos os combinados existentes.

## Gerenciar
A seção Gerenciar permite à administração escolar:

- acessar o painel de Administração do sistema.

#  en

## Plan
The Plan section allow us:

- to create a new indicator to be monitored over time, including charts;
- to define objectives that ate connected to and might impact these indicators; and
- to plan specific school based actions - specific activities - which can lead to attaining these objective.

## Check
The Check section allow us:

- to monitor the measured indicators over time;
- to view defined objectives; and
- to view actions and collect evidence of implementation;

## Agreements
The Agreements section allow us:

- to define new school agreements based on school meetings or extracted from previously successful strategies;
- to define new agreements based on the success of actions evaluated in the system;
- to list all the agreements that have been already defined.

## Manage
The Manage section allow school staff:

- to access the administration painel.
