### ISSUE TITLE
Verificar formatação da impressão dos DataTables

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#11]
Campo "prioridade" sai com informações erradas.

**Comment by glaubersp** [comment]
Selects não podem ser campos imprimíveis em DataTable.
Verificar a distribuição da largura das colunas (é possível configurar na mão?)

**Comment by glaubersp** [comment]
Remover as colunas com botões e selects da impressão.
Verificar se é possível adicionar cabeçalho

**Comment by greevin** [comment]
As colunas citadas foram removidas da impressão e do Excel exportado. É possível adicionar o cabeçalho na impressão e especificar de acordo com o que for necessário. Fonte: https://github.com/yajra/laravel-datatables/issues/759

Com relação ao cabeçalho no Excel, ainda estou verificando se é possível fazer isso.

**Comment by greevin** [comment]
Feito.
