### ISSUE TITLE
Alterar menus

### ISSUE THREAD

**Issue by glaubersp** [glaubersp/CEAP#13]
Renomear menus como abaixo:

> Principal
> Planejamento
-- Planejar nova Ação
-- Definir novo Objetivo
-- Cadastrar novo Indicador
> Acompanhamento
-- Painel
-- Ações (antigo Coletar Evidências)
-- Objetivos
-- Indicadores
> Combinados
-- Criar Combinados
-- Listar Combinados

**Comment by greevin** [comment]
Feito.
