### ISSUE TITLE
Redefinir tela Acompanhamento / Indicadores

### ISSUE THREAD

**Issue by glaubersp** [glaubersp/CEAP#16]
Colunas: Seleção, Indicador, Ciclo, Escopo, Valor, Interação

Na coluna Valor, listar o valor do registro mais recente.
Na coluna Interação, adicionar botões:

Botão | Ícone | Tooltip
------ | ----- | --------
1 | + | Definir novo Objetivo
2 | ?? | Cadastrar novo valor
3 | Histograma | Histórico de Registros

**Comment by greevin** [comment]
Feito, mas ainda está faltando definir a rota para o 'Histórico de Registro' e definir os ícones de cada botão.
