### ISSUE TITLE
Alterar navegação do Planejamento

### ISSUE THREAD

**Issue by glaubersp** [glaubersp/CEAP#18]
Alterar a navegação para as telas do Planejamento, permitindo ir direto para a criação de um novo item.

- Definir novo Indicador deve ter 3 botões:

Botão | Ícone | Tooltip
------ | ----- | --------
Salvar | ?? | Salvar
Salvar e Definir Objetivo | ?? | Salvar e Definir Objetivo
Cancelar | X | Cancelar

- Definir novo Objetivo deve ter 3 botões:

Botão | Ícone | Tooltip
------ | ----- | --------
Salvar | ?? | Salvar
Salvar e Definir Ação | ?? | Salvar e Definir Ação
Cancelar | X | Cancelar

- Planejar nova Ação deve ter 3 botões:

Botão | Ícone | Tooltip
------ | ----- | --------
Salvar | ?? | Salvar
Salvar e Coletar Evidência | ?? | Salvar e Coletar Evidência
Cancelar | X | Cancelar

**Comment by greevin** [comment]
Feito.
