### ISSUE TITLE
Criar modal para Avaliar ações

### ISSUE THREAD

**Issue by glaubersp** [glaubersp/CEAP#19]
Avaliação deve ter 2 campos: Implementação e Resultado.
- Implementação deve ser um dropdown com as opções: Não implementado, Implementado Parcialmente, Implementado totalmente
- Resultado deve usar a avaliação baseada em 5 estrelas.

Incluir select com a pergunta: "Haverá novo ciclo?".
Se o select for marcado, após salvar a avaliação, deverá ser direcionado para a tela de Planejar nova Ação com os dados desta ação, deixando o campo de data de avaliação a ser preenchido.

**Comment by greevin** [comment]
O modal foi arrumado, só está faltando acrescentar a parte do 'Haverá novo ciclo?'.

**Comment by greevin** [comment]
Referente ao 'Haverá novo ciclo?' será resolvido na issue #22.
