### ISSUE TITLE
Telas de visualização (show) devem usar labels e não possuir elementos de edição

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#24]
Para quem não tem permissão de edição, a página deve ser limpa, fundo branco, sem qualquer indicativo de edição (e.g. drop down list, etc.).

**Comment by glaubersp** [comment]
Alterar as views "show" e utilizar labels para exibir os valores atualmente exibidos nos elementos

**Comment by greevin** [comment]
Feito. Todas as telas de visualização foram modificadas para só usarem os labels em vez dos inputs.
