### ISSUE TITLE
Tela de listar evidências deve renderizar HTML da descrição

### ISSUE THREAD

**Issue by glaubersp** [glaubersp/CEAP#31]
Provavelmente é preciso usar labels para os dados e usar um elemento que renderize o html para este campo.

**Comment by greevin** [comment]
Foi necessário adicionar um InnerHTML para que fosse possível renderizar o HTML que está armazenado no banco de dados. Realizei alguns testes para que não fosse possível adicionar código malicioso através do mesmo, por exemplo: adicionar um alert() através dessa div.
