### ISSUE TITLE
Implementar ciclos para ações e indicadores

### ISSUE THREAD

**Issue by glaubersp** [glaubersp/CEAP#33]
**Indicadores**
- A periodicidade do ciclo do indicador deve definir quando ele expira e somente a partir deste momento deve ser possível atualizar o seu valor.

**Ações**
- O ciclo de uma ação deve ser fechado pela avaliação.
- Quando executada a avaliação, deve-se optar por duplicar a ação em novo ciclo ou criar um combinado associado a esta ação.

**Comment by tamielbr** [comment]
Fazendo a avaliação agora, me parece realmente necessário poder indicar que ciclo estou avaliando. Por exemplo, se ela é de semestre 1 - 2017, e não foi implementada, nada impede que fique "viva" para que seja implementada em semestre 2 - 2017.

**Comment by glaubersp** [comment]
No modal de avaliar Ação, incluir checkbox com a pergunta "Haverá novo ciclo?".
Se o select for marcado, após salvar a avaliação, deverá ser direcionado para a tela de Planejar nova Ação com os dados desta ação, deixando o campo de data de avaliação a ser preenchido.

**Comment by greevin** [comment]
Isso já foi implementado na nova versão. Como não estamos mais trabalhando com o conceito de datas, quando marcar a opção 'Duplicar Ação?', ele cria uma nova ação adicionando o próximo semestre na coluna 'Período'.

![ceap test_actions 1](https://user-images.githubusercontent.com/7833013/34681900-696c6f76-f484-11e7-9c10-992c0e0aa925.png)
