### ISSUE TITLE
Quadrado para "tooltip" é confuso

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#40]
Poderia ser um "?"

![screen shot 2017-04-23 at 19 50 54](https://cloud.githubusercontent.com/assets/3904166/25318122/31c92ed0-285e-11e7-8d17-fbf1a83ead2c.png)

**Comment by greevin** [comment]
Faltava o link /var/www/html/fonts -> /var/www/html/ceap/fonts no servidor.
