### ISSUE TITLE
Estrela não aparece na escala

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#42]
Imagino que pode ser relacionado a #40 - problema pode ser no loading da imagem. 

![screen shot 2017-04-23 at 19 56 27](https://cloud.githubusercontent.com/assets/3904166/25318144/1306a0f8-285f-11e7-9071-056f3c878ac6.png)

Testado no Firefox Mac 52.

**Comment by greevin** [comment]
Faltava o link /var/www/html/fonts -> /var/www/html/ceap/fonts no servidor.
