### ISSUE TITLE
Erro na catalogação de evidências

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#48]
A sequência foi a abaixo.

![screen shot 2017-04-23 at 20 49 40](https://cloud.githubusercontent.com/assets/3904166/25318504/8d20196c-2866-11e7-866f-83e9dc0d8b6b.png)

![screen shot 2017-04-23 at 20 49 24](https://cloud.githubusercontent.com/assets/3904166/25318505/8d526c82-2866-11e7-835c-b4470541b8ef.png)

Depois voltei e tentei somente editar o texto, sem arquivo e recebi o mesmo erro. Voltei e tentei algumas vezes, e parece que com pouco texto vai. Há algum limite?

**Comment by tamielbr** [comment]
É problema com o campo de texto. Consegui fazer upload de arquivo em outro, sem texto descritivo, sem maiores problemas.

**Comment by greevin** [comment]
Corrigido o tipo de dado no banco para que possa aceitar texto com mais de 65.535 caracteres. Os seguintes campos foram alterados para o tipo LONGTEXT (o tipo em parênteses representa o tipo antigo desse campo):

actions - details (VARCHAR)
evidences - details (VARCHAR)
goal_evaluations - justification (TEXT)
goals - justification (TEXT)
indicators - description (TEXT)
