### ISSUE TITLE
Depois de criar evidências, devo poder voltar aonde parei

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#54]
Agora, o único jeito de voltar é clicando no _breadcrumb_ ou no menu. O problema é que quando volto, não volto onde parei - o sistema me volta na lista de ações como se estivesse acessando o menu pela primeira vez. Se eu estava na página 3, volto pra 1, e tenho que clicar em "próximo" duas vezes. Possível mudar?

**Comment by tamielbr** [comment]
O mesmo acontece quando seleciono prioridade. Volto para a primeira página da lista de ações e não onde eu estou (se estou mais pra frente).

**Comment by tamielbr** [comment]
Temos o mesmo problema com as ações. Se mudo a prioridade, volto pra a página inicial e não onde estou. Por exemplo, quero mudar a prioridade para BAIXA mas depois editar. Tenho que encontrar denovo a mesma ação.

**Comment by greevin** [comment]
Sim, isso foi corrigido em todas as tabelas para que, ao entrar em algum item e voltar, ele continue no estado anterior.

**Comment by glaubersp** [comment]
Eu vou subir no servidor até o fim da noite, Tel. As correções aqui são fechadas quando subimos pra versão de desenvolvimento no GitHub =)
