### ISSUE TITLE
Corrigir 'Acompanhar Indicadores'

### ISSUE THREAD

**Issue by greevin** [glaubersp/CEAP#65]
- Implementar Histórico de Registro para os tipos 'Rooms' e 'School';
- Implementar gráfico para os dois tipos acima;
- Verificar os caminhos de retornos para a tela 'Acompanhar Indicadores' e garantir que eles coloquem o indicatorGroupId com session()->flash ao invés de passar para o render().
- Fazer esta mesma verificação para o Criar indicador.

**Comment by glaubersp** [comment]
Trocar o datatable único por 3 datatables separados, um para cada tipo, para que o saveState funcione corretamente.
Alterar a exibição e a carga dos datatables de acordo com o change do select.

**Comment by glaubersp** [comment]
Optei por deixar o histórico de Registro fora da tabela. Na prática, será o Atualizar registro que, para quem não tem permissões, será apenas de visualização e não de edição.
