### ISSUE TITLE
Dropdown não está em ordem alfabética

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#67]
Acho que é o melhor jeito de organizar, senão fica difícil encontrar o tópico.

![screen shot 2017-06-01 at 10 05 44](https://cloud.githubusercontent.com/assets/3904166/26681008/ef0de1e0-46b1-11e7-8447-c59f081219ea.png)

**Comment by tamielbr** [comment]
Não sei se é possível fazer um ``search box`` que permite uma única seleção. Pode ser ainda melhor.

**Comment by greevin** [comment]
A caixa de seleção está em ordem alfabética e, ao clicar nela, aparece um campo para pesquisar e selecionar apenas uma opção.

![select](https://cloud.githubusercontent.com/assets/7833013/26688323/b266c416-46c8-11e7-956c-e4d786b4eba0.png)
