### ISSUE TITLE
Prioridade versus avaliação na lista

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#68]
@glaubersp - me pergunto se na hora de utilizar a lista, não é mais útil organizar pelo que já foi avaliado ou não. Vamos conversar sobre isso, pensando inclusive na relação do que já foi avaliado e se vai ser "arquivado" se for o caso.

![screen shot 2017-06-01 at 10 09 09](https://cloud.githubusercontent.com/assets/3904166/26681118/5f97e06e-46b2-11e7-90c6-8dc0087b4026.png)

**Comment by glaubersp** [comment]
Atualização foi alterado para data de expiração e está como ordenação inicial.
