### ISSUE TITLE
Erro em texto no relatório PDF

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#70]
![screen shot 2017-06-01 at 10 25 09](https://cloud.githubusercontent.com/assets/3904166/26681767/a1828e8c-46b4-11e7-9bb0-43e692c8c517.png)

**Comment by glaubersp** [comment]
Já está corrigido no repositório.
Eu atualizei os PDFs que estão no Nextcloud pra você pegar a versão mais nova.
