### ISSUE TITLE
Ordem das evidências por tempo

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#71]
Acho importante para saber o que foi colocado por útlimo.

![screen shot 2017-06-01 at 10 30 19](https://cloud.githubusercontent.com/assets/3904166/26682001/5795b302-46b5-11e7-8e99-3c8ee9729955.png)

**Comment by greevin** [comment]
Na tabela de 'Evidências', foi adicionado o campo 'Atualização' para mostrar quando ocorreu a última alteração da informação. Eu decidi deixar apenas a data para melhor visualização, com isso, sempre o primeiro item da lista é o que foi atualizado recentemente baseado no campo 'updated_at' do banco.

![evidences1](https://cloud.githubusercontent.com/assets/7833013/26694723/cc123358-46de-11e7-8f8b-b0024db0b240.png)
