### ISSUE TITLE
Datatable salva valor das pesquisas 

### ISSUE THREAD

**Issue by glaubersp** [glaubersp/CEAP#76]
Datatable salva estado e mantém o campo de pesquisa.
Talvez seja melhor colocar JavaScript pra limpar ao carregar. Isso pode conflitar, então talvez um botão do lado da pesquisa.

**Comment by glaubersp** [comment]
Mudar a cor do campo de pesquisa quando não estiver vazio parece melhor

**Comment by greevin** [comment]
Seria algo relacionado a isso https://datatables.net/reference/option/stateDuration ?

**Comment by glaubersp** [comment]
A configuração já está pra -1. Basta agora alterar o JS para deixar a caixa de pesquisa vermelha quando contiver texto.
