### ISSUE TITLE
Juntar botão de regsitro em uma única linha

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#79]
Juntar ``atualizar`` e ``adicionar`` na linha de baixo, juntos, fica mais intuitivo. 

![screen shot 2017-06-26 at 10 30 03](https://user-images.githubusercontent.com/3904166/27541490-7b8d5658-5a5a-11e7-9a4d-84466694f999.png)

**Comment by greevin** [comment]
Arrumado a posição dos botões para que ele mostre os botões 'Adicionar Registro' e 'Atualizar Registro' separado dos botões de ações.

![sem titulo](https://user-images.githubusercontent.com/7833013/27638282-170ee968-5be9-11e7-8269-dbaf29d0e50c.png)
