### ISSUE TITLE
Arrumar inserção de dados de indicadores

### ISSUE THREAD

**Issue by glaubersp** [glaubersp/CEAP#80]
Colocar 0 como padrão, além da tooltip
Ao retornar de validação errada, está indo para tela de update no lugar de store.
As tabelas estão redimensionando e aparecendo o botão + no lugar de aparecer como tabela.

**Comment by greevin** [comment]
Adicionado o 'value=0.0' no input dos indicadores dos três tipos;
Ao salvar, eles estava indo pro lugar correto, só a mensagem de validação que estava escrito errado;
As tabelas foram arrumadas adicionado um 'width: 100%';

Bônus: foi descoberto um bug ao carregar a tabela do 'Atualizar Registro' do tipo 'Salas' que não estava aparecendo. O mesmo já foi arrumado.
