### ISSUE TITLE
Arrumar geração de gráficos

### ISSUE THREAD

**Issue by glaubersp** [glaubersp/CEAP#81]
- [x] Percorrer todos os valores para achar máximo e mínimo para gerar a mesma escala no Y.
Se for zero, não gerar o gráfico.
- [ ] Implemementar botão para permitir definir os intervalos máximo e mínimo? Isto pode obrigar a remover pontos do gráfico!

**Comment by glaubersp** [comment]
@tamielbr , os gráficos zerados não estão aparecendo. Aquele que vc viu tinha um 0.2 como dado. Arrumei no banco. 
Na prática, a escala dos gráficos do CEAP vai de 0 a 100, pq eu normalizo pelo menor e pelo maior valor de todos os pontos e tem entrada válida com 100%. O 0% não está gerando gráficos, mas achei que pra efeito de comparação ao longo do tempo, melhor que a escala comece em 0.

Fiquei me perguntando se, por efeito de comparação, não é mais sensato fixar a escala de 0 a 100 de uma vez. O que acha?

**Comment by tamielbr** [comment]
Poderia ser, para padronizar, mas o problema é que isso gera a impressão de pouca melhoria ou piora. 72 para 86 é significativo, mas no gráfico parece insignificante. Por isso acho que a média pode ser boa - por outro lado, sempre ficarem entre uns 10-80, o que nõa é muito diferente. Existe algum botão que permite (nesse plugin) que o usuário escolha a escala?

**Comment by glaubersp** [comment]
Posso implementar um. 

Glauber M. Cabral

Mestre em Ciência da Computação pela UNICAMP

Enviado via iPhone

**Comment by tamielbr** [comment]
Deixemos pra wish e por hora vamos de 0 a 100, assim terminamos as outras ações. Pode ser?

**Comment by glaubersp** [comment]
Tranquilo.

Glauber M. Cabral

Mestre em Ciência da Computação pela UNICAMP

Enviado via iPhone
