### ISSUE TITLE
Strings de tradução faltantes

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#83]
Não sei onde elas se encontram, me apontem por favor.

![screen shot 2017-06-28 at 15 22 35](https://user-images.githubusercontent.com/3904166/27653539-c0645616-5c15-11e7-9fa3-eb27d5b93ae8.png)

**Comment by greevin** [comment]
Tel, essa parte que não está traduzida é produzida pelo próprio plugin da tabela por isso não apareceu naquela página de tradução.
