### ISSUE TITLE
Criar documentação do projeto

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#85]
- [x] Descrição geral do software, no próprio github (Instalação, frameworks e versões, dependências, etc.)
- [ ] Manual básico de uso (pensar em vídeos narrados + texto)

**Comment by glaubersp** [comment]
Adicionada descrição no README.
Publicado o pacote no Packagist e criada uma documentação de instalação inicial.
Pensar em criar um script de automação de instalação, se necessário.

**Comment by tamielbr** [comment]
Já em andamento. Vou remover issue.
