### ISSUE TITLE
Erro no datatables dos combindados

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#86]
Ao dar um sort por "ações relacionadas" na tabela dos combinados, recebo erro.

![screen shot 2017-07-24 at 15 56 23](https://user-images.githubusercontent.com/3904166/28539593-a7df607c-7088-11e7-910b-f6df97c7db3b.png)

**Comment by glaubersp** [comment]
A ordenação foi desabilitada momentaneamente.
Pra funcionar sobre esta coluna, é preciso reimplementation o datatable e não usar o plugin que utilizei. Criei a issue #87 para isso.
