### ISSUE TITLE
Gráfico ordena resultados por valor

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#88]
Ano de 2017 (último) fica no meio. Todos estão assim.

![screen shot 2017-07-28 at 19 20 00](https://user-images.githubusercontent.com/3904166/28740854-f8b421d0-73e0-11e7-957b-2ac60f0f2725.png)

**Comment by glaubersp** [comment]
Já arrumei. Estou terminando de arrumar o rótulo dos gráficos do SARESP.
