### ISSUE TITLE
Customizar tooltips

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#91]
pode compartilhar o arquivo texto ou interface que eu vejo?

**Comment by glaubersp** [comment]
É o mesmo esquema das outras strings, @tamielbr.
Endereço: https://ceap.nied.unicamp.br/ceap/translations
Group: tooltips.
Se trocar a língua no site do CEAP vc consegue ver as strings no lugar das tooltips e aí consegue buscar na página de tradução.
