### ISSUE TITLE
Definir modelo de Permissões

### ISSUE THREAD

**Issue by glaubersp** [glaubersp/CEAP#92]
O sistema suporta Usuários, Papéis e Permissões.

A ideia das permissões é poder associá-las as ações de interface e, além das 3 permissões padrões do sistema, foram criadas permissões para ler, criar, editar, armazenar (trash), restaurar, deletar definitivamente.

Permissões definidas:
- view-backend: permite acessar o backend de administração do sistema
- manage-users': permite gerenciar usuários
- manage-roles': permite gerenciar papéis
- can-create: permissão para criar/salvar itens
- can-view: permissão para visualizar itens
- can-edit: permissão para alterar itens
- can-trash: permissão para apagar itens (por padrão, a remoção armazena, mas não apaga do banco)
- can-restore: permissão para restaurar itens apagados
- can-delete: permissão para apagar definitivamente do banco. Ainda não há interface para fazer isto!

Papéis definidos:
- Administrador (padrão, tem todas as permissões);
- Diretor (similar ao Administrador),
- Secretária (similar ao professor)
- Professor (can-create, can-edit, can-view, can-trash, can-restore)

**Comment by tamielbr** [comment]
Como fica a diferença entre ``diretor`` e ``admin``, ou podemos concatenar? O mesmo vale pra `prof`` e ``secretaria``. Acho importante definir se teremos diferenças.

**Comment by glaubersp** [comment]
No contexto da FA  e dessas permissões acima, eu só vejo dois papéis, na prática. No entanto, eu acho melhor definir no código as permissões para as tarefas e aí definir quais permissões cada papel tem. Acredito que facilmente é possível pensar em locais que esses quatro papéis terão comportamento diferentes pra essas permissões que defini. E talvez venhamos a precisar de outras permissões. Papéis eu acho difícil mudar, a menos que passemos a ter aluno/pais e eles passem a poder visualizar através de login.

**Comment by glaubersp** [comment]
Pensei em um outro modelo de permissões:
Permissões definidas:
- view-backend: permite acessar o backend de administração do sistema
- manage-users': permite gerenciar usuários
- manage-roles': permite gerenciar papéis
- **can-plan: permissão para acessar telas de planejamento/criação/remoção de ações/objetivos/indicadores/combinados**
- **can-view: permissão para visualizar a parte de acompanhamentos e combinados**
- **can-check: permissão para coletar evidências**
- **can-evaluate: permissão para avaliar ações**

Todo mundo que vai ver pode imprimir gráfico/exportar csv? 
Se sim, pode-se manter apenas can-view. 
Se não, podemos criar um can-export para exportar/imprimir.

**Comment by glaubersp** [comment]
Este modelo de permissão lega a uma pergunta sobre a interface: faz sentido combinado estar separado em um terceiro menu com criar/listar ou deveríamos separar estas duas ações de combinados e colocar como quarto item nos respectivos menus Adicionar e Acompanhar?

**Comment by tamielbr** [comment]
me parece que faz sentido incorporar. isso saberíamos com testes, mas logicamente, faz sentido para mim.

**Comment by tamielbr** [comment]
vc sugeriu esse esquema novo em substituição ao anterior ou complementar?

**Comment by glaubersp** [comment]
Complementar. Eu acho que tem algumas ações facilmente agregáveis em criar, editar e apagar, mas outras eu vejo que devem ser específicas porque não necessariamente serão apenas para quem pode editar( por exemplo, coletar evidência e avaliar)

**Comment by tamielbr** [comment]
@greevin/ @glaubersp preciso opinar aqui ou fechamos?
