### ISSUE TITLE
Ao criar uma nova ação, mesmo com responsável ele aceita e reclama

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#93]
Adicionei ação, e esqueci da data de ``término estimada``. Eu havia colocado ``responsável``, ele não salvou. Quando voltei para colocar ``término estimada``, ele reclamou da falta de ``responsável``. Adicionei e quando salvei ele foi para a próxima tela com erro (mesmo que a ação esteja cadastrada):

![screen shot 2017-09-01 at 09 11 56](https://user-images.githubusercontent.com/3904166/29969261-af7efabe-8ef5-11e7-8dec-4bdd6dba170b.png)

**Comment by greevin** [comment]
A questão foi resolvida alterando a forma com o erro aparece, conforme #97.
