### ISSUE TITLE
Diferenciar o final de uma ação

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#94]
Precisamos pensar nos diferentes "fins" de uma ação:
- Finalizado - ou seja, terminou porque tinha que terminar - por exemplo, professor orientador no começo do ano, já foi finalizado, podemos considerar como sucesso, feito.
- Arquivado - fica pra memória, não deu certo, foi mal implementado, etc. - alimentação, parte das ações não foram boas, mas devem ficar na memória.
- Removido - não vale nem guardar - qualuquer coisa aventada que sequer avançou e não vai mais ser usada (podemos ver isso como arquivado também, mas pensar em como diferenciar isso)

Desses, acho que não temos o ``finalizado``, que é importante para tirar da lista, mas garantir que fique visível. Vamos conversar sobre como implementar isso.

**Comment by tamielbr** [comment]
E ainda, pensar em como ficamos com ações como o jornal, que são perenes. Podemos:
- Cadastrar a criação de cada edição como uma ação (cansativo)
- Ou criar ação perene, sem data de término, que é "fechada" eventualmente.

**Comment by tamielbr** [comment]
E ver como isso dialoga com "combinados" (no sentido de ações perenes).

**Comment by glaubersp** [comment]
Só precisamos de dois: Arquivado (guarda) e Deletar (remove completamente).
