### ISSUE TITLE
Implementar a impressão de combinados

### ISSUE THREAD

**Issue by glaubersp** [glaubersp/CEAP#95]
- Permitir a seleção de combinados para impressão
- Fixar a formatação (minimizar as folhas utilizadas e retirar dados secundários).

**Comment by glaubersp** [comment]
@greevin Veja meu commit acima. O CSS está com problemas pra quebrar o quarto botão de uma linha.
Acho que precisa forçar o quarto botão a voltar para o início da linha.

**Comment by greevin** [comment]
A questão dos botões em linha foi substituído por um dropdown com todos os botões referente a exportação dos dados.
