### ISSUE TITLE
Permitir "ver ação" dentro da avaliação

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#96]
Quando coloco uma avaliação em uma ação que quero depois arquivar, tenho que voltar para trás com o back do browser até chegar na lista de ações e ai sim, clicar no nome e depois apagar. 

Sugestões: título (e.g. "Utilizar o Whatsapp...") ou _breadcrumb_ (``Avaliação ação / Nome linkável) tenha a ação clicável, assim posso imediatamente ir à ela e arquivar.

![screen shot 2017-12-14 at 13 35 39](https://user-images.githubusercontent.com/3904166/34000333-224aba44-e0d4-11e7-88c9-6545f2802f90.png)

**Comment by greevin** [comment]
'Avaliar Ações' acabou virando um modal que dá pra acessar diretamente pela lista de 'Acompanhar Ações'. Além disso, 'Evidências' e 'Avaliação' agora ficam dentro de 'Exibir Ação' quando uma ação é selecionada.
