### ISSUE TITLE
Criar combinado sem assunto limpa campos do formulário

### ISSUE THREAD

**Issue by tamielbr** [glaubersp/CEAP#97]
Quando crio um combinado, e esqueço de colocar um ``assunto``, ele dá mensagem de erro (correta) mas limpa alguns dos campos (``envolvidos`` e ``ações``) no refresh.

![screen shot 2017-12-14 at 13 55 23](https://user-images.githubusercontent.com/3904166/34001222-930d85b6-e0d6-11e7-8b73-88758d365148.png)

**Comment by greevin** [comment]
Essa parte foi corrigida na nova versão. Agora, a página não é mais recarregada para mostrar o erro, ele mostra o erro na parte do formulário que está faltando, como no exemplo abaixo do formulário do 'Combinados'. 

![ceap test_agreements_create](https://user-images.githubusercontent.com/7833013/34037922-a7098e20-e171-11e7-8724-e29c1983e3aa.png)
